export const QUERY_KEY = {
    GET_ALL_STATUS: "GET_ALL_STATUS",
    GET_ALL_SOURCE: "GET_ALL_SOURCE",
    GET_SOCIAL_MEDIA: "GET_SOCIAL_MEDIA",
    GET_ALL_SERVICES: "GET_ALL_SERVICES",
    GET_ALL_CUSTOMER: "GET_ALL_CUSTOMER"
};
